# Generated by Django 5.2.4 on 2026-01-29 23:55

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=restaurant.models.get_local_now),
        ),
    ]
