# Generated by Django 5.2.4 on 2026-02-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_menuitem_alter_booking_id_alter_menu_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
